groups/api/urls.py
from .views import api_create_groupview,api_detail_group,api_join_group,api_leave_group,ApiPostListView,ViewAllPosts
from django.urls import path

app_name= 'groups'

urlpatterns = [
    path('alljoined/',ApiPostListView.as_view(),name='list'),
    path('all/',ViewAllPosts.as_view(),name='list'),

    path('new/',api_create_groupview,name='create'),
    path('detail/<slug:slug>/',api_detail_group,name='detail'),
    path('join/<slug:slug>/',api_join_group,name='join'),
    path('leave/<slug:slug>/',api_leave_group,name='leave'),

]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>/',views.DetailGroup.as_view(),name='single'),
    path('all/',views.ListGroup.as_view(),name='all'),
    path('join/<slug:slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path
from . import  views

app_name='posts'

urlpatterns = [

    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('all/',views.ListPost.as_view(),name='all'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='by_user'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),


]

socialclone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view


from . import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include("django.contrib.auth.urls")),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),

    path('login_success/',views.login.as_view(),name='login_success'),
    path('thanks/',auth_view.LoginView.as_view(template_name='accounts/login.html'),name='thanks'),



    #REST FRAMEWORK URLS
    path('api/posts/',include('posts.api.urls',namespace='posts_api')),
    path('api/accounts/',include('accounts.api.urls',namespace='accounts_api')),
    path('api/groups/',include('groups.api.urls',namespace='groups_api')),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify
# from accounts.models import UserProfile
import misaka
# Create your models here.

User = get_user_model()


from django import  template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True) #allow_unicode=True , allows slug to accept unicode letters in addition to from ASCII
    description = models.TextField(default='',blank='',)
    description_html = models.TextField(editable=False,blank=True,default='')
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)

        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})
#Define a get_absolute_url() method to tell Django how to calculate the canonical URL for an object.
# To callers, this method should appear to return a string that can be used to refer to the object over HTTP.


    class Meta:
         ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user_profile = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together =('group','user_profile')



'''

The related_name attribute specifies the name of the reverse relation from the User model back to your model.

If you don't specify a related_name, Django automatically creates one using the name of your model with the suffix _set, for instance User.map_set.all().

If you do specify, e.g. related_name=maps on the User model, User.map_set will still work, but the User.maps. syntax is obviously a bit cleaner and less clunky;
so for example, if you had a user object current_user, you could use current_user.maps.all() to get all instances of your Map model that have a relation to current_user.

'''


'''
DIFFERENCE B/W TextField and CharField

It's a difference between RDBMS's varchar (or similar) — those are usually specified with a maximum length,
 and might be more efficient in terms of performance or storage — and text (or similar) types — those are usually limited
  only by hardcoded implementation limits (not a DB schema).
  
  A good rule of thumb is that you use CharField when you need to limit the maximum length, TextField otherwise.
'''

groups/api/views.py
from django.utils.text import slugify
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView,CreateAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from ..models import Group,GroupMember
from django.db import  IntegrityError
from .serializers import GroupSerializer
from rest_framework.generics import ListAPIView
from django.db.models import Q
from django.contrib.auth import models
from rest_framework.filters import SearchFilter,OrderingFilter


class ViewAllPosts(ListAPIView):

    serializer_class = GroupSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Group.objects.all()



class ApiPostListView(ListAPIView):

    serializer_class = GroupSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = Group.objects.filter(members=self.request.user)
        return queryset
    # pagination_class = PageNumberPagination
    # filter_backends = (SearchFilter, OrderingFilter)
    # search_fields = ('title', 'message', 'user__username')



@api_view(['POST',])
@permission_classes((IsAuthenticated,))
def api_create_groupview(request):
    account = request.user
    grp = Group()
    if request.method == "POST":
        slug = slugify(request.data['name'])
        newdata = request.data.copy()
        newdata['slug'] = slug
        newdata['posts'] = []
        serializer = GroupSerializer(grp,data=newdata)
        if serializer.is_valid():
            serializer.save()
            grp.members.add(account)

            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_detail_group(request,slug):
    try:
        grp = Group.objects.get(slug=slug)
    except Group.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        serializer = GroupSerializer(grp)
        return Response(serializer.data)


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_join_group(request,slug):
    try:
        grp = Group.objects.get(slug=slug)
    except Group.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        data={}
        try:
            GroupMember.objects.create(user_profile=request.user, group=grp)
        except IntegrityError:
            data['Response']="User already joined group"
        else:
            data['Response'] = "User joined the group"
        return Response(data)



@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_leave_group(request,slug):
    try:
        grp = Group.objects.get(slug=slug)
    except Group.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        data={}
        try:
            membership = GroupMember.objects.filter(user_profile=request.user,group__slug=slug).get()
        except GroupMember.DoesNotExist:
            data['Response']="User does not exist in group"
        else:
            membership.delete()
            data['Response'] = "User left the group"
        return Response(data)

groups/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView,CreateView,DetailView,RedirectView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.contrib import messages
from django.urls import  reverse_lazy
from . import models


class ListGroup(ListView):
    model = models.Group


# create view requires a <name>_form.html , ex:- group_form.html file
class CreateGroup(LoginRequiredMixin,CreateView):
    fields = ('name', 'description')
    model = models.Group

    def form_valid(self, form):
        instance = form.save(commit=False)

        instance.save()
        instance.members.add(self.request.user.user_profile)
        return super().form_valid(form)

    # def get_success_url(self):
    #     group = get_object_or_404(models.Group, slug=self.kwargs.get('slug'))
    #     try:
    #         models.GroupMember.objects.create(user=self.request.user, group=group)
    #     except IntegrityError:
    #         messages.warning(self.request, "User already joined")
    #     else:
    #         messages.success(self.request, "User joined the group")
    #
    #     return reverse('groups:single',kwargs={'slug':self.slug})

    # def get(self, request, *args, **kwargs):

    #     return super().get(self,*args,**kwargs)
#slug_field¶
#The name of the field on the model that contains the slug. By default, slug_field is 'slug'
# slug_url_kwarg¶
# The name of the URLConf keyword argument that contains the slug. By default, slug_url_kwarg is 'slug'.


class DetailGroup(LoginRequiredMixin,DetailView):
    model = models.Group
    #the name in the url that defines the slug for example 'books/<slug:slug>/
    slug_url_kwarg = 'slug'


    slug_field = 'slug'
    # the name of the field in the model that contains the slug


    # def get(self, request, *args, **kwargs):
    #     group = get_object_or_404(models.Group,slug=self.kwargs.get('slug'))
    #     try:
    #         models.GroupMember.objects.create(user=self.request.user,group=group)
    #     except IntegrityError:
    #         messages.warning(self.request,"User already joined")
    #     else:
    #         messages.success(self.request,"User joined the group")
    #     return super().get(self,*args,**kwargs)




class JoinGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        group = get_object_or_404(models.Group,slug=self.kwargs.get('slug'))

        try:
             models.GroupMember.objects.create(user_profile=self.request.user.user_profile,group=group)
        except IntegrityError:
            messages.warning(self.request,'user already registered')
        else:
            messages.success(self.request,'user joined the group')


        return super().get(self,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:all')

    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMember.objects.filter(user_profile=self.request.user.user_profile,group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'user no longer in group')
        else:
            membership.delete()
            messages.success(self.request,'user left the group successfully')


        return super().get(self,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block main_content %}
<div class="container">
    {% block pre_group %} {% endblock %}
    {% block group_content %} {% endblock %}
    {% block post_group %} {% endblock %}
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pre_group %}
<div class="col">
<h1>{{group.name}}</h1>
<h2>members:{{group.members.count}}</h2>

<div class="content">
    {% if user.user_profile in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-success">
            <span class="glyphicon glyphicon-remove-circle">
                Leave
            </span>
        </a>
    {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
             <span class="glyphicon glyphicon-ok-circle">
                Join
            </span>
        </a>
    {% endif %}
</div>
</div>
    {% endblock %}



{% block group_content %}
    <div class="col-md-8">
        {% if group.posts.count == 0 %}
            <h2> No post in this group. </h2>
        {% else %}
            {% for post in group.posts.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}

{% load bootstrap3 %}

{% block group_content %}
<div class="col">
<h4>Create A New Group</h4>
  <form method="POST"  id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
	</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pre_group %}
<div class="">
    <div class="content">
        {% if user.is_authenticated %}
            <h2>Welcome Back
            <a href="{% url 'posts:by_user' username=user.username %}">@{{user.username}}</a>
            </h2>
        {% endif %}
         <h2>Groups</h2>
        <p>Welcome to groups page</p>
    </div>

    {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
            <span class="glyphicon glyphicon-plus-sign">Create New Group!</span>
        </a>
    {% endif %}

</div>
{% endblock %}

{% block group_content %}
<div class="">
    <center><h1> Groups</h1></center>

 </div>
<div class="h">
    {% for group in object_list %}
       <div class="jumbotron">
            <a class="" href="{% url 'groups:single' slug=group.slug %}">
            <h5 class="display-4" >{{group.name|capfirst}}</h5>
            <div class="">
                <p class="">{{group.description}}</p>
            </div>
            <div class="row">
                <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>

                </div>

        </a>
       </div>

    {% empty %}
        <p>No groups yet</p>
        <a class="btn btn-primary" type="button" href="{% url 'groups:create' %}">Create New</a>
    {% endfor %}
</div>

{% endblock %}