accounts/urls.py
from django.urls import path
from  django.contrib.auth import views as auth_view
from . import  views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup.as_view(),name='signup'),
    path('login/',auth_view.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
]

posts/urls.py
from django.urls import path
from . import  views

app_name='posts'

urlpatterns = [

    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('all/',views.ListPost.as_view(),name='all'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='by_user'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),


]

socialclone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view


from . import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include("django.contrib.auth.urls")),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),

    path('login_success/',views.login.as_view(),name='login_success'),
    path('thanks/',auth_view.LoginView.as_view(template_name='accounts/login.html'),name='thanks'),



    #REST FRAMEWORK URLS
    path('api/posts/',include('posts.api.urls',namespace='posts_api')),
    path('api/accounts/',include('accounts.api.urls',namespace='accounts_api')),
    path('api/groups/',include('groups.api.urls',namespace='groups_api')),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Social Clone</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'home' %}">Social Clone</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a class="nav-link" href="{% url 'posts:all' %}">Posts </a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'posts:create' %}">Create Post </a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'groups:all' %}"> Groups <span class="sr-only">(current)</span></a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'groups:create' %}">Create Group </a></li>-


        </ul>
              <ul class="navbar-nav">
                  <form class="form-inline my-2 my-lg-0">
<!--                  <input class="form-control mr-sm-2" type="search" placeholder="Search">-->
<!--                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
                  </form>
                  {% if user.is_authenticated %}
                    <li class="nav-item active"> <a class="nav-link" href="{% url 'posts:by_user' user.username %}">{{user.username}}</a> </li>
                    <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a></li>

                  {% else %}

                     <li class="nav-item active"> <a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                     <li class="nav-item active"> <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>

                  {% endif %}
              </ul>
          </div>

    </nav>

{% block main_content %}

{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block main_content %}

<div class="container">
    <div class="jumbotron ">
           <h1 class="display-2">Welcome, {{user.username}}</h1>
        <img src={{user.avatar}} />
        <hr class="my-4">


    </div>

</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block main_content %}
<div class="container">
    <center>
        <h1 >welcome {{ user.username }} </h1>
        <img src="">
        <a href="{% url 'groups:all' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">View Groups</a>
    </center>

</div>

{% endblock %}

templates/thankyou.html
{% extends 'base.html' %}

{% block main_content %}
<h1>thanks for logging in see you later</h1>
{% endblock %}