posts/api/urls.py
from .views import PostList,api_update_postview,api_create_postview,api_delete_postview,api_detail_view
from django.urls import path


app_name = 'posts'

urlpatterns = [
    path('all/',PostList.as_view(),name='postlist'),
    path('update/<slug:slug>/',api_update_postview,name='postupdate'),
    path('create/',api_create_postview,name='postcreate'),
    path('delete/<int:pk>/',api_delete_postview,name='postdelete'),
    path('detail/<slug:slug>/',api_detail_view,name='postdetail'),


]

posts/urls.py
from django.urls import path
from . import  views

app_name='posts'

urlpatterns = [

    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('all/',views.ListPost.as_view(),name='all'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='by_user'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),


]

socialclone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view


from . import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include("django.contrib.auth.urls")),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),

    path('login_success/',views.login.as_view(),name='login_success'),
    path('thanks/',auth_view.LoginView.as_view(template_name='accounts/login.html'),name='thanks'),



    #REST FRAMEWORK URLS
    path('api/posts/',include('posts.api.urls',namespace='posts_api')),
    path('api/accounts/',include('accounts.api.urls',namespace='accounts_api')),
    path('api/groups/',include('groups.api.urls',namespace='groups_api')),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from groups.models import Group
# from accounts.models import UserProfile
from django.urls import reverse
from django.utils.text import slugify
import misaka
from  django.utils import  timezone
User = get_user_model()
# Create your models here.



class Post(models.Model):
    title = models.CharField(max_length=200,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True,editable=False,default=slugify(title))
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    # auto_now_add will set to current time only while creation of object
    # auto_now will set to current_time every time the object is updated/saved.
    updated_at = models.DateTimeField(auto_now=True,editable=False)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',blank=True,null=True,on_delete=models.CASCADE)

    def get_absolute_url(self):
        print("called")
        return reverse('posts:single',kwargs={'username':self.user.user.username,'pk':self.pk})


    def __str__(self):
        return self.message + ' ' + self.slug

    def save(self,*args,**kwargs):
        self.message_html=misaka.html(self.message)
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['-created_at']
       # unique_together = ['user','message',]

posts/forms.py
from django import  forms
from .models import Post
from groups.models import Group


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','message','group']

    def __init__(self,*args,**kwargs):
        self.user = kwargs.pop('user',None)
        super(PostForm,self).__init__(*args,**kwargs)
        self.fields['group'].queryset = Group.objects.filter(members=self.user.user_profile)

posts/api/views.py
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from ..models import Post
from .serializers import PostSerializer,PostUpdateSerializer
from django.db.models import  Q
from django.contrib.auth import models
from rest_framework.filters import SearchFilter,OrderingFilter


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_detail_view(request,slug):
    try:
        userpost = Post.objects.get(slug=slug)
        # print(userpost.group.name)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "GET":
        serializer = PostSerializer(userpost)
        return Response(serializer.data)


class PostList(ListAPIView):
    serializer_class = PostSerializer
    queryset = Post.objects.all()
    authentication_classes = ()
    permission_classes = ()
    # authentication_classes = (TokenAuthentication,)
    # permission_classes = (IsAuthenticated,)


    # def get_queryset(self):
    #
    #     user = self.request.user
    #     gps=[]
    #     # for group in user.user_groups.all():
    #     #     gps.append(group.group)
    #     # Q(group__in=gps) |
    #     return Post.objects.filter(Q(group__in=gps) | Q(user=self.request.user))
    # pagination_class = PageNumberPagination
    # filter_backends = (SearchFilter,OrderingFilter)
    # search_fields = ('title','message','user__username')


class PostUpdate(APIView):

    def put(self,request,pk):
        post = Post.objects.get(pk)
        grp=post.group
        usr=post.user
        serializer = PostUpdateSerializer(post,data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT',])
@permission_classes((IsAuthenticated,))
def api_update_postview(request,slug):
    try:
        post = Post.objects.get(slug=slug)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    requser = request.user

    if post.user != requser:
        return Response({'Response':"you don't have correct permissions to edit "})

    if request.method == "PUT":
        serializer = PostUpdateSerializer(post,data=request.data)
        #print(serializer.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data["success"]="update was successful"
            return Response(data=data)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE',])
@permission_classes((IsAuthenticated,))
def api_delete_postview(request,pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    requser = request.user
    if post.user != requser:
        return Response({'Response': "you dont have correct permissions to delete "})

    if request.method == "DELETE":
        operation = post.delete()
        data = {}
        if operation:
            data["success"] = "delete successful"
        else:
            data["failure"] = "delete failed"
        return Response(data=data)


@api_view(['POST',])
@permission_classes((IsAuthenticated,))
def api_create_postview(request):
    account = request.user
    post = Post(user=account)

    if request.method == "POST":
        serializer = PostSerializer(post,data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

#    account = User.objects.get(pk=1)

posts/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,DetailView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import  SelectRelatedMixin
from  django.db import IntegrityError
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib import messages
from . import  models
from .forms import PostForm

User = get_user_model()


class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = models.Post
    fields = ['message']
    template_name_suffix = '_update_form'


"""
select_related is used for a foreign key or related field which is one to one relation ship.
It helps to reduce the number of queries since it creates a join and fetches the data hence reducing the queries and runtime

SelectRelatedMixin however allows us to use select_related in out class definition
https://betterprogramming.pub/django-select-related-and-prefetch-related-f23043fd635d 
"""

class ListPost(LoginRequiredMixin,SelectRelatedMixin,ListView):
    model = models.Post
    select_related=("user","group")

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data()
        context['listgroups']=self.request.user.user_profile.user_groups.all()
        return context


class CreatePost(LoginRequiredMixin,CreateView):
    form_class = PostForm
    model = models.Post

    def get_form_kwargs(self):
        kwargs = super(CreatePost, self).get_form_kwargs()

        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            self.object.user = self.request.user.user_profile
            self.object.save()
        except IntegrityError:
            print("error occurred")
        else:
            print("success here")
        return super().form_valid(form)


class PostDetail(SelectRelatedMixin,DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__user__username__iexact=self.kwargs.get('username'))


class UserPosts(ListView):

    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()


    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        context['post_user']= self.post_user
        return context


class DeletePost(LoginRequiredMixin,SelectRelatedMixin,DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,"Post Deleted")
        return super().delete(self,request,*args,**kwargs)

posts/templates/posts/_post.html
    <div  class="container pt-4 pb-4 text-dark  border-bottom " >
        <div class=" "><h1 class="display-4" onclick="{% url 'posts:single' username=post.user.user.username pk=post.pk %}">{{post.title |safe}}</h1> </div>
        <div class="">
            <div class="lead"><p class="lead">{{post.message_html|safe}}</p> </div>
        </div>

        <div class="row">
            {% if post.group.slug %}
            <div class="col-sm-4"><a href="{% url 'groups:single' slug=post.group.slug %}" >{{post.group.name}}</a></div>
            {% endif %}
            <div class="col-sm-4">created: {{post.created_at}}</div>
            <div class="col-sm-4">updated: {{post.updated_at}}</div>
            <div class="col-sm-4">updated: {{post.user}}</div>
        </div>
</div>


<!--<div class="container">-->
<!--    <div class="well">-->
<!--        <div class="media">-->
<!--            <div class="media-body">-->
<!--                <h1>{{ post.title |safe }}</h1>-->
<!--                <p class="text-right">By {{post.user.username}}</p>-->
<!--                <p>{{ post.message_html |safe }}</p>-->
<!--                <ul class="list-inline list-unstyled">-->
<!--  			<li><span><i class="glyphicon glyphicon-calendar"></i> {{post.created_at}} </span></li>-->
<!--                     {% if post.group %}-->
<!--                        <span class="group-name"> in {{ post.group.name }}</span>-->
<!--                    {% endif %}-->

<!--			</ul>-->

<!--    <div class="row">-->
<!--    <div class="col-md-4">-->
<!--                {% if user.is_authenticated and post.user == user %}-->
<!--                    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-sm btn-outline-danger">-->
<!--                        DELETE-->
<!--                    </a>-->
<!--                {% endif %}-->
<!--        </div>-->
<!--         <div class="col-md-4">-->
<!--                {% if user.is_authenticated and post.user == user %}-->
<!--                    <a href="{% url 'posts:update' pk=post.pk %}" title="update" class="btn btn-sm btn-outline-success">-->
<!--                        UPDATE-->
<!--                    </a>-->
<!--                {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block main_content %}
<div class="container">
    {% block pre_post %} {% endblock %}
    {% block post_content %} {% endblock %}
    {% block post_post %} {% endblock %}
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}


<!--<div class="posts">-->
<!--    {% include 'posts/_post.html' with post=object hide_delete=True %}-->
<!--</div>-->

<form method="post">
    {% csrf_token %}

    <div class="jumbotron">
    <h3>Are you sure you want to delete ?</h3>


        <p style="font-size:300px" class="">{{ post.message_html |safe }}</p>

    <input type="submit" value="confirm" class="btn btn-danger btn-large">
     <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-success btn-large btn-default" >CANCEL</a>
        </div>
</form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div>
    {% include 'posts/_post.html' %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}



{% block post_content %}
<h1> Create Post</h1>

<form method="post" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="create" class="btn btn-primary">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% load humanize %}

{% block pre_pst %}
<div class="col-md-8">

    {% if user.is_authenticated %}
        <div class="card card-with-shadow">

            <div class="content">
                <h3 class="title"> Your Groups{{ mship }}</h3>
                <ul class="list-unstyled">

                    {% for member_group in listgroups  %}
                        <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}">{{member_group.group.name}}</a> </li>
                    {% empty %}
                        <li class="group li-with-bullet"><p>No groups yet</p></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <h2>User not logged in</h2>
    {% endif %}
</div>
{% endblock %}

{% block post_content %}

<div class="list-group">
    {% for post in object_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}
</div>



{% endblock %}

posts/templates/posts/post_update_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block post_content %}
<h1> Update Post</h1>

<form method="post" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="update" class="btn btn-primary">
</form>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block pre_post %}
<div class="col-md-4">
    <h1>@{{post_user.username|title}}</h1>
</div>
<br>
{% endblock %}
{% block post_content %}
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
        <br>
    {% endfor %}
{% endblock %}